# Generated by Django 4.0.6 on 2022-07-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Simple Post', max_length=255),
        ),
    ]
